spring.application.name=backend

server.port=${PORT:8080}

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/railway
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración general
spring.main.allow-bean-definition-overriding=true

# Límites de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

spring.jackson.serialization.write-dates-as-timestamps=false


# HikariCP - Pool de conexiones saludable
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.maximum-pool-size=5    