spring.application.name=backend

# Configuración H2 (Base de datos local ultrarrápida)
spring.datasource.url=jdbc:h2:file:./data/isla_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crear tablas automáticamente basado en las clases Java
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Consola para ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Evitar errores de definición
spring.main.allow-bean-definition-overriding=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB
