-- ✅ USUARIOS
INSERT INTO USUARIOS (MATRICULA, PASSWORD, ROL, BLOQUEADO)
SELECT 'riempy', 'admin123', 'ADMIN', FALSE
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE MATRICULA = 'riempy');

INSERT INTO USUARIOS (MATRICULA, PASSWORD, ROL, BLOQUEADO)
SELECT 'Ricardo', 'usuario123', 'VENDEDOR', FALSE
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE MATRICULA = 'Ricardo');

INSERT INTO USUARIOS (MATRICULA, PASSWORD, ROL, BLOQUEADO)
SELECT 'Olga', 'oligator', 'VENDEDOR', FALSE
WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE MATRICULA = 'Olga');

-- ✅ PRODUCTOS
INSERT INTO PRODUCTO (CODIGO, NOMBRE, STOCK, PRECIO_COMPRA, PRECIO_VENTA, CATEGORIA, REGISTRADO_POR_MATRICULA)
SELECT 'Ip15OR', 'Funda de iPhone 15 Tipo Original', 4, 45.0, 200.0, 'Fundas', 'riempy'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE CODIGO = 'Ip15OR');

INSERT INTO PRODUCTO (CODIGO, NOMBRE, STOCK, PRECIO_COMPRA, PRECIO_VENTA, CATEGORIA, REGISTRADO_POR_MATRICULA)
SELECT 'Bat201', 'Power bank 20000mAh 22.5W MAX', 1, 199.0, 400.0, 'Fundas', 'riempy'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE CODIGO = 'Bat201');

INSERT INTO PRODUCTO (CODIGO, NOMBRE, STOCK, PRECIO_COMPRA, PRECIO_VENTA, CATEGORIA, REGISTRADO_POR_MATRICULA)
SELECT 'Bat101', 'Power bank 10000mAh 22.5W MAX', 2, 135.0, 300.0, 'Fundas', 'riempy'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE CODIGO = 'Bat101');

-- ✅ VENTAS
INSERT INTO VENTA (CANTIDAD, CODIGO_PRODUCTO, FECHA_VENTA, NOMBRE_PRODUCTO, PRECIO_VENTA, TOTAL, VENDEDOR_MATRICULA, PRECIO_COMPRA)
SELECT 1, 'Ip15OR', '2026-03-05 13:35:42.968986', 'Funda de iPhone 15 Tipo Original', 150.0, 150.0, 'riempy', 45.0
WHERE NOT EXISTS (SELECT 1 FROM VENTA WHERE ID = 20);